CREATE TABLE IF NOT EXISTS investment_report_versions (
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id             VARCHAR(32) NOT NULL,
    conversation_id     BIGINT,
    ticker              VARCHAR(32) NOT NULL,
    user_query          TEXT,
    recommendation      VARCHAR(32),
    report_version      INT NOT NULL,
    data_snapshot_hash  VARCHAR(64) NOT NULL,
    context_hash        VARCHAR(64) NOT NULL,
    model_tier          VARCHAR(16),
    model_name          VARCHAR(64),
    report_json         JSON NOT NULL,
    generated_at        DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_at          DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_report_snapshot_context (user_id, ticker, data_snapshot_hash, context_hash),
    INDEX idx_report_user_created (user_id, created_at),
    INDEX idx_report_user_ticker_version (user_id, ticker, report_version),
    INDEX idx_report_hashes (data_snapshot_hash, context_hash)
) ENGINE=InnoDB;
