CREATE TABLE IF NOT EXISTS research_tasks (
    id                        BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id                   VARCHAR(32) NOT NULL,
    conversation_id           BIGINT,
    idempotency_key           VARCHAR(191) NOT NULL,
    ticker                    VARCHAR(32) NOT NULL,
    status                    VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    stage                     VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    attempts                  INT NOT NULL DEFAULT 0,
    lease_token               VARCHAR(64),
    payload_json              JSON NOT NULL,
    error_message             TEXT,
    result_report_version_id  BIGINT,
    started_at                DATETIME,
    completed_at              DATETIME,
    heartbeat_at              DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_at                DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at                DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_research_task_idempotency (idempotency_key),
    INDEX idx_research_task_user_created (user_id, created_at),
    INDEX idx_research_task_status_stage (status, stage),
    INDEX idx_research_task_heartbeat (status, heartbeat_at),
    INDEX idx_research_task_ticker_created (ticker, created_at)
) ENGINE=InnoDB;
